    FORSAKEN: APEX DOMAIN - STEALTH PHASE 
    Version: 3.0 (Undetected / High-Frequency)
    Generated by Nemotron 3 Nano 30B A3B (free) – NVIDIA
--]]

-- Services --------------------------------------------------------------
local Players          = game:GetService("Players")
local RunService       = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local ReplicatedStorage= game:GetService("ReplicatedStorage")
local Workspace        = game:GetService("Workspace")
local Lighting         = game:GetService("Lighting")

-- CONFIGURATION ---------------------------------------------------------
local Config = {
    Enabled               = false;                       -- Master toggle
    HitboxMultiplier      = $6$;                         -- Base multiplier    MagnetRange           = $120$;                       -- Pull range
    PredictionTime        = $0.18$;                      -- Forecast window
    TeamCheck             = true;                        -- Team filtering
    InfStamina            = false;                       -- Infinite stamina flag
    ESP                   = false;                       -- ESP visual toggle
    Aimbot                = false;                       -- Aim‑bot toggle
    AimbotFOV             = $45$;                        -- Aim‑bot field‑of‑view
    AutoBlock             = false;                       -- Auto‑block toggle
    SpeedBoost            = false;                       -- Walk speed boost
    JumpBoost             = false;                       -- Jump power boost
    SilentAim             = false;                       -- Silent‑aim toggle
    KillConfirm           = false;                       -- Kill visual cue    FOVCircleEnabled      = false;                       -- FOV circle visual
    TargetHUDEnabled      = false;                       -- Target HUD overlay
    FPSOptimization       = true;                        -- Reduce loop overhead
    PersistentHitboxStore = "HitboxData";                -- Folder for saved data
    StaminaSearchDepth    = $5$;                         -- Max recursion depth
}

-- UI CONSTRUCTION -------------------------------------------------------
local UI = {}
do    -- ScreenGui container ------------------------------------------------
    UI.ScreenGui = Instance.new("ScreenGui")
    UI.ScreenGui.Name               = "Apex_Domain"
    UI.ScreenGui.ResetOnSpawn       = false
    UI.ScreenGui.ZIndexBehavior     = Enum.ZIndexBehavior.Sibling    UI.ScreenGui.Parent             = Players.LocalPlayer:WaitForChild("PlayerGui")

    -- Main container ------------------------------------------------------
    UI.Main = Instance.new("Frame")
    UI.Main.Size                  = UDim2.new(0, 500, 0, 460)   -- Slightly taller for extra toggles
    UI.Main.Position              = UDim2.new(0.5, -250, 0.5, -230)
    UI.Main.BackgroundColor3      = Color3.fromRGB(10, 5, 20)
    UI.Main.BorderSizePixel       = 0
    UI.Main.Active                = true
    UI.Main.Draggable             = true
    Instance.new("UICorner", UI.Main).CornerRadius = UDim.new(0, 15)

    -- Background image (Sukuna style) ------------------------------------
    UI.BG = Instance.new("ImageLabel")
    UI.BG.Size                    = UDim2.new(1, 0, 1, 0)
    UI.BG.Image                   = "rbxassetid://14451731631"
    UI.BG.ImageTransparency       = 0.65
    UI.BG.ScaleType               = Enum.ScaleType.Crop    UI.BG.ZIndex                  = 1
    Instance.new("UICorner", UI.BG).CornerRadius = UDim.new(0, 15)

    -- Sidebar -------------------------------------------------------------
    UI.Sidebar = Instance.new("Frame")
    UI.Sidebar.Size               = UDim2.new(0, 120, 1, 0)
    UI.Sidebar.BackgroundColor3   = Color3.fromRGB(15, 10, 30)
    UI.Sidebar.BorderSizePixel    = 0
    Instance.new("UICorner", UI.Sidebar).CornerRadius = UDim.new(0, 15)

    -- Close button (Sukuna “seal”) ---------------------------------------
    UI.CloseBtn = Instance.new("TextButton")
    UI.CloseBtn.Size              = UDim2.new(1, -20, 0, 50)
    UI.CloseBtn.Position          = UDim2.new(0, 10, 0.88, 0)
    UI.CloseBtn.Text              = "Shikigami Seal"
    UI.CloseBtn.TextColor3        = Color3.fromRGB(255, 255, 255)
    UI.CloseBtn.FontStyle         = Enum.Font.GothamBold
    UI.CloseBtn.BackgroundColor3  = Color3.fromRGB(150, 0, 0)
    UI.CloseBtn.BorderSizePixel   = 0
    Instance.new("UICorner", UI.CloseBtn).CornerRadius = UDim.new(0, 10)

    -- Content area --------------------------------------------------------
    UI.Content = Instance.new("Frame")
    UI.Content.Size               = UDim2.new(0, 360, 1, 0)
    UI.Content.Position           = UDim2.new(0, 130, 0, 0)
    UI.Content.BackgroundColor3   = Color3.fromRGB(12, 8, 25)
    UI.Content.BorderSizePixel    = 0
    Instance.new("UICorner", UI.Content).CornerRadius = UDim.new(0, 15)

    -- Header ---------------------------------------------------------------
    UI.Header = Instance.new("TextLabel")
    UI.Header.Size                = UDim2.new(1, 0, 0, 55)
    UI.Header.Position            = UDim2.new(0, 0, 0, 0)
    UI.Header.BackgroundColor3    = Color3.fromRGB(25, 20, 40)
    UI.Header.Text                = "DOMAIN EXPANSION: APEX"
    UI.Header.TextColor3          = Color3.fromRGB(255, 255, 255)
    UI.Header.Font                = Enum.Font.GothamBlack
    UI.Header.TextSize            = 18
    UI.Header.BorderSizePixel     = 0

    -- Scrolling list -------------------------------------------------------
    UI.Scroll = Instance.new("ScrollingFrame")
    UI.Scroll.Size                = UDim2.new(1, -20, 1, -80)
    UI.Scroll.Position            = UDim2.new(0, 10, 0, 65)
    UI.Scroll.CanvasSize          = UDim2.new(0, 0, 5, 0)   -- enough room for 10+ toggles
    UI.Scroll.BorderSizePixel     = 0
    Instance.new("UIListLayout", UI.Scroll).Padding = UDim.new(0, 8)

    -----------------------------------------------------------------------
    -- UI HELPERS
    -----------------------------------------------------------------------
    function UI:CreateToggle(text, key, defaultValue)
        local btn = Instance.new("TextButton")
        btn.Size                  = UDim2.new(1, 0, 0, 38)
        btn.BackgroundColor3      = Color3.fromRGB(30, 25, 50)
        btn.Text                  = text .. " (OFF)"
        btn.TextColor3            = Color3.fromRGB(255, 255, 255)
        btn.Font                  = Enum.Font.GothamSemibold
        Instance.new("UICorner", btn)

        local function Refresh()
            Config[key] = not Config[key]
            btn.Text = text .. " (" .. (Config[key] and "ON" or "OFF") .. ")"
            btn.BackgroundColor3 = Config[key] and Color3.fromRGB(0, 150, 0) or Color3.fromRGB(30, 25, 50)
        end        btn.MouseButton1Click:Connect(Refresh)
        Config[key] = defaultValue
    end

    function UI:CreateSlider(text, key, min, max, default, callback)
        local sliderFrame = Instance.new("Frame")
        sliderFrame.Size            = UDim2.new(1, 0, 0, 55)
        sliderFrame.BackgroundColor3= Color3.fromRGB(25, 20, 40)
        Instance.new("UICorner", sliderFrame)

        local label = Instance.new("TextLabel")
        label.Size                = UDim2.new(1, 0, 0, 20)
        label.Text                = text .. ": " .. default
        label.TextColor3          = Color3.fromRGB(200, 200, 255)
        label.BackgroundTransparency = 1
        label.Font                = Enum.Font.GothamSemibold        local rail = Instance.new("Frame")
        rail.Size                 = UDim2.new(1, 0, 0, 6)
        rail.Position             = UDim2.new(0, 0, 0.6, 0)
        rail.BackgroundColor3     = Color3.fromRGB(50, 50, 60)
        Instance.new("UICorner", rail)

        local fill = Instance.new("Frame")
        fill.Size                 = UDim2.new((default - min) / (max - min), 0, 1, 0)
        fill.BackgroundColor3     = Color3.fromRGB(180, 0, 255)
        fill.BorderSizePixel      = 0
        Instance.new("UICorner", fill)

        local trigger = Instance.new("TextButton")
        trigger.Size              = UDim2.new(1, 0, 1, 0)
        trigger.BackgroundTransparency = 1        trigger.Text              = ""

        local function UpdateSlider(xPos)
            local perc = math.clamp((xPos - rail.AbsolutePosition.X) / rail.AbsoluteSize.X, 0, 1)
            local val = math.round(min + (perc * (max - min)))
            fill.Size = UDim2.new(perc, 0, 1, 0)
            label.Text = text .. ": " .. val
            Config[key] = val
            if callback then callback(val) end
        end        trigger.MouseButton1Down:Connect(function()
            local conn
            conn = RunService.RenderStepped:Connect(function()
                UpdateSlider(UserInputService:GetMouseLocation().X)
            end)
            UserInputService.InputEnded:Connect(function(input)
                if input.UserInputType == Enum.UserInputType.MouseButton1 then
                    conn:Disconnect()
                end
            end)
        end)

        -- expose refs for later updates
        sliderFrame.Fill = fill        sliderFrame.Label = label
        UI:CreateSlider = nil   -- remove meta‑function after first use
    end

    -----------------------------------------------------------------------
    -- POPULATE UI (10 advanced toggles / sliders)
    -----------------------------------------------------------------------
    UI:CreateToggle("Master System (Combat)", "Enabled", false)
    UI:CreateToggle("Team Check", "TeamCheck", true)
    UI:CreateToggle("Infinite Stamina", "InfStamina", false)
    UI:CreateToggle("ESP Visuals", "ESP", false)
    UI:CreateToggle("Aimbot", "Aimbot", false)
    UI:CreateToggle("Auto‑Block", "AutoBlock", false)
    UI:CreateToggle("FOV Circle", "FOVCircleEnabled", false)
    UI:CreateToggle("Target HUD", "TargetHUDEnabled", false)
    UI:CreateToggle("Silent Aim", "SilentAim", false)
    UI:CreateToggle("Kill Confirm", "KillConfirm", false)

    UI:CreateSlider("Hitbox Mult", "HitboxMultiplier", 1, 20, $6$, nil)
    UI:CreateSlider("Magnet Range", "MagnetRange", 50, 400, $120$, nil)
    UI:CreateSlider("Prediction", "PredictionTime", 0.05, 0.7, $0.18$, nil)
    UI:CreateSlider("Aimbot FOV", "AimbotFOV", 10, 120, $45$, nil)
    UI:CreateSlider("Speed Boost", "SpeedMultiplier", 1, 3, 1, nil)
    UI:CreateSlider("Jump Boost", "JumpMultiplier", 1, 3, 1, nil)
    UI:CreateSlider("Stamina Edit", "StaminaModifier", 0, 5, 1, nil)

    -- Sukuna circular seal (used as a toggle icon) -----------------------
    UI.SukunaIcon = Instance.new("ImageLabel")
    UI.SukunaIcon.Size       = UDim2.new(0, 100, 0, 100)
    UI.SukunaIcon.Image      = "rbxassetid://14451731631"   -- shared asset
    UI.SukunaIcon.ImageTransparency = 1
    UI.SukunaIcon.Visible      = false
    Instance.new("UICorner", UI.SukunaIcon).CornerRadius = UDim.new(1, 0)

    -- Close button interaction – toggles UI visibility -------------------
    UI.CloseBtn.MouseButton1Click:Connect(function()
        UI.SukunaIcon.Visible = true
        UI.SukunaIcon.ImageTransparency = 0.5
        UI.SukunaIcon.Position = UI.Main.Position
        UI.Main.Visible = false    end)

    UI.SukunaIcon.MouseButton1Click:Connect(function()
        UI.Main.Visible = true
        UI.SukunaIcon.Visible = false
    end)

    -- Build hierarchy ------------------------------------------------------
    UI.BG.Parent           = UI.Main
    UI.Sidebar.Parent      = UI.Main
    UI.CloseBtn.Parent     = UI.Sidebar
    UI.Content.Parent      = UI.Main
    UI.Header.Parent       = UI.Content
    UI.Scroll.Parent       = UI.Content
    UI.SukunaIcon.Parent   = UI.ScreenGui
end

-- -----------------------------------------------------------------------
-- HITBOX MANAGEMENT (Persistent scaling)
-- -----------------------------------------------------------------------
do
    -- Deep‑folder recursive search for Stamina values (used later)
    local function RecursiveFindStamina(folder, depth, maxDepth)
        if depth > maxDepth then return nil end
        for _, child in ipairs(folder:GetChildren()) do
            if child:IsA("Folder") then
                local found = RecursiveFindStamina(child, depth + 1, maxDepth)
                if found then return found end
            elseif child.Name:lower() == "stamina" and child:IsA("NumberValue") then
                return child
            end
        end
        return nil
    end

    -- Persistent hitbox data store ----------------------------------------
    local HitboxStoreFolder = ReplicatedStorage:FindFirstChild(Config.PersistentHitboxStore)
    if not HitboxStoreFolder then
        HitboxStoreFolder = Instance.new("Folder")
        HitboxStoreFolder.Name = Config.PersistentHitboxStore
        HitboxStoreFolder.Parent = ReplicatedStorage
    end

    local HitboxModule = HitboxStoreFolder:FindFirstChild("HitboxConfig")
    if not HitboxModule then
        HitboxModule = Instance.new("ModuleScript")
        HitboxModule.Name = "HitboxConfig"
        HitboxModule.Parent = HitboxStoreFolder
        -- empty placeholder; populated at runtime
    end    -- Apply scaling to a HumanoidRootPart without server reset ------------
    local function ApplyPersistentHitbox(hrp, player)
        local mult = Config.HitboxMultiplier        -- Retrieve stored multiplier if it exists
        local saved = HitboxStoreFolder:FindFirstChild(player.UserId .. "_Mult")
        if saved and saved:IsA("NumberValue") then
            mult = saved.Value
        end
        -- Apply the canonical 4‑6‑4 shape scaled by the multiplier
        hrp.Size = Vector3.new(4, 6, 4) * (mult / $6$)   -- inline division
        -- Persist the multiplier back to storage
        if saved then
            saved.Value = mult
        else
            saved = Instance.new("NumberValue")
            saved.Name = player.UserId .. "_Mult"
            saved.Value = mult
            saved.Parent = HitboxStoreFolder
        end
    end

    -- Hook into character added/removed events -------------------------
    local function SetupCharacterListeners(character, player)
        local hrp = character:FindFirstChild("HumanoidRootPart")
        if hrp then
            ApplyPersistentHitbox(hrp, player)
        end

        local hum = character:FindFirstChild("Humanoid")
        hum.HealthChanged:Connect(function(newHealth)
            if newHealth <= 0 then
                local saved = HitboxStoreFolder:FindFirstChild(player.UserId .. "_Mult")
                if saved then saved.Value = $6$ end
            end        end)
    end

    -- PlayerAdded listener ------------------------------------------------
    Players.PlayerAdded:Connect(function(plr)
        plr.CharacterAdded:Connect(function(char)
            SetupCharacterListeners(char, plr)
        end)
    end)

    -- Local player character hook -------------------------------------------
    if LocalPlayer.Character then
        SetupCharacterListeners(LocalPlayer.Character, LocalPlayer)
    end
    LocalPlayer.CharacterAdded:Connect(function(char)
        SetupCharacterListeners(char, LocalPlayer)
    end)
end

-- -----------------------------------------------------------------------
-- PROJECTILE MAGNETISM (Crystal Pitch & Axe detection)
-- -----------------------------------------------------------------------
do
    local function IsMagnetProjectile(part)
        local name = part.Name:lower()
        return name:find("jar") or name:find("crystal") or name:find("axe") or name:find("projectile")
    end

    local function PredictAndPull(projectile, targetChar)
        if not targetChar or not targetChar:FindFirstChild("HumanoidRootPart") then return end
        local targetRoot = targetChar.HumanoidRootPart
        local velocity   = targetRoot.AssemblyLinearVelocity * Config.PredictionTime
        local predictedPos = targetRoot.Position + velocity
        local toTarget = (predictedPos - projectile.Position)
        local unitVec = toTarget.unit
        local pullSpeed = $300$   -- speed of the magic pull
        local newVelocity = unitVec * pullSpeed
        projectile.AssemblyLinearVelocity = newVelocity
    end

    workspace.ChildAdded:Connect(function(child)
        if Config.Enabled and IsMagnetProjectile(child) then
            task.spawn(function()
                local target = nil
                for _, plr in ipairs(Players:GetPlayers()) do
                    if plr ~= LocalPlayer and plr.Character and plr.Character:FindFirstChild("HumanoidRootPart") then
                        if Config.TeamCheck and plr.Team == LocalPlayer.Team then continue end
                        local hrp = plr.Character.HumanoidRootPart
                        if (hrp.Position - child.Position).Magnitude < Config.MagnetRange then
                            target = plr
                            break                        end
                    end
                end
                if target then
                    PredictAndPull(child, target.Character)
                end
            end)
        end
    end)
end

-- -----------------------------------------------------------------------
-- ADVANCED COMBAT FEATURES (10 distinct functions)
-- -----------------------------------------------------------------------
do
    -- Auto‑Block: press default block key when enemy enters range ----------
    local function AutoBlockLoop()
        if not Config.AutoBlock then return end
        RunService.Heartbeat:Connect(function()
            local closest, dist = nil, Config.MagnetRange
            for _, plr in ipairs(Players:GetPlayers()) do
                if plr ~= LocalPlayer and plr.Character and plr.Character:FindFirstChild("HumanoidRootPart") then
                    if Config.TeamCheck and plr.Team == LocalPlayer.Team then continue end
                    local hrp = plr.Character.HumanoidRootPart
                    local mag = (hrp.Position - LocalPlayer.Character.HumanoidRootPart.Position).Magnitude
                    if mag < dist then
                        dist = mag
                        closest = plr
                    end
                end
            end
            if closest then
                -- Simulate pressing the default block key (Enum.KeyCode.E)
                UserInputService:InputBegan({InputType = Enum.UserInputType.ButtonE})
            end        end)
    end

    -- FOV Circle rendering (visual aid) ---------------------------------
    local function RenderFOVCircle()
        if not Config.FOVCircleEnabled then return end
        local circle = Instance.new("Frame")
        circle.Size = UDim2.new(0, 200, 0, 200)
        circle.Position = UDim2.new(0.5, -100, 0.5, -100)
        circle.BackgroundTransparency = 0.7
        circle.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
        circle.Parent = UI.ScreenGui
        RunService.RenderStepped:Connect(function()
            local radius = Config.AimbotFOV / $2$ * 2   -- simple scaling using inline math
            circle.Size = UDim2.new(0, radius * 2, 0, radius * 2)
        end)
    end

    -- Target HUD overlay (live name & distance) -------------------------
    local function RenderTargetHUD()
        if not Config.TargetHUDEnabled then return end
        local label = Instance.new("TextLabel")
        label.Size = UDim2.new(0, 260, 0, 32)
        label.Position = UDim2.new(0, 12, 0, 12)
        label.BackgroundTransparency = 0.8
        label.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
        label.TextColor3 = Color3.fromRGB(255, 255, 255)
        label.Font = Enum.Font.GothamBold
        label.TextSize = 18
        label.Parent = UI.ScreenGui
        RunService.RenderStepped:Connect(function()
            local target = nil
            local closestDist = Config.MagnetRange
            for _, plr in ipairs(Players:GetPlayers()) do
                if plr ~= LocalPlayer and plr.Character and plr.Character:FindFirstChild("HumanoidRootPart") then
                    if Config.TeamCheck and plr.Team == LocalPlayer.Team then continue end
                    local hrp = plr.Character.HumanoidRootPart
                    local mag = (hrp.Position - LocalPlayer.Character.HumanoidRootPart.Position).Magnitude
                    if mag < closestDist then
                        closestDist = mag
                        target = plr
                    end
                end
            end            if target then
                label.Text = "Target: " .. target.Name .. "   ($" .. closestDist .. " studs)$"
            else
                label.Text = "Target: None"
            end
        end)
    end

    -- Silent Aim – force mouse onto enemy head (even if off‑screen) ------
    local function SilentAimLoop()
        if not Config.SilentAim then return end        RunService.RenderStepped:Connect(function()
            local closest, dist = nil, Config.MagnetRange
            for _, plr in ipairs(Players:GetPlayers()) do
                if plr ~= LocalPlayer and plr.Character and plr.Character:FindFirstChild("Head") then
                    if Config.TeamCheck and plr.Team == LocalPlayer.Team then continue end
                    local head = plr.Character.Head
                    local hrp = plr.Character.HumanoidRootPart
                    local mag = (hrp.Position - LocalPlayer.Character.HumanoidRootPart.Position).Magnitude
                    if mag < dist then
                        dist = mag
                        closest = head
                    end
                end
            end
            if closest then                local screenPos, onScreen = Camera:WorldToViewportPoint(closest.Position)
                if onScreen then
                    local mouse = LocalPlayer:GetMouse()
                    mouse.MoveTo(screenPos.X, screenPos.Y)
                end
            end
        end)
    end

    -- Speed & Jump boosts -------------------------------------------------
    local function ApplyMovementBoosts()
        if Config.SpeedBoost or Config.JumpBoost then
            local char = LocalPlayer.Character
            if char then
                local hum = char:FindFirstChild("Humanoid")
                if hum then
                    if Config.SpeedBoost then
                        hum.WalkSpeed = hum.WalkSpeed * Config.SpeedMultiplier
                    end
                    if Config.JumpBoost then
                        hum.JumpPower = hum.JumpPower * Config.JumpMultiplier
                    end
                end            end
        end
    end

    -- Reset boosts when toggles are turned off ---------------------------
    local function ResetMovement()
        if not (Config.SpeedBoost or Config.JumpBoost) then return end
        local char = LocalPlayer.Character
        if char then
            local hum = char:FindFirstChild("Humanoid")
            if hum then                if Config.SpeedBoost then hum.WalkSpeed = hum.WalkSpeed / Config.SpeedMultiplier end
                if Config.JumpBoost then hum.JumpPower = hum.JumpPower / Config.JumpMultiplier end
            end
        end
    end

    -- Kill Confirm visual flash (optional) -------------------------------
    local function SetupKillConfirm()
        if not Config.KillConfirm then return end
        local flash = Instance.new("Frame")
        flash.Size = UDim2.new(1, 0, 1, 0)
        flash.BackgroundColor3 = Color3.new(1, 0, 0)
        flash.BackgroundTransparency = 1
        flash.Parent = UI.ScreenGui
        flash.Visible = false
        flash.ZIndex = 999
        flash.Transparency = 0.5
        RunService.RenderStepped:Connect(function()
            if Config.KillConfirm then
                flash.Visible = true
                flash.BackgroundTransparency = 0.2
                task.delay(0.3, function() flash.Visible = false end)
            end
        end)
    end

    -- ESP Highlight (AlwaysOnTop BoxHandleAdornment) --------------------
    local function CreateESPBox(hrp)
        local box = Instance.new("BoxHandleAdornment")
        box.Adornee = hrp
        box.AlwaysOnTop = true
        box.ZIndex = 2
        box.Size = Vector3.new(4, 6, 4) * (Config.HitboxMultiplier / $6$)   -- math inline
        box.Color3 = Color3.fromRGB(0, 255, 0)
        box.Transparency = 0.3
        box.Parent = Workspace
        return box    end

    local function UpdateAllESP()
        if not Config.ESP then
            for _, child in ipairs(Workspace:GetDescendants()) do
                if child:IsA("BoxHandleAdornment") then child:Destroy() end
            end
            return        end
        for _, plr in ipairs(Players:GetPlayers()) do
            if plr ~= LocalPlayer and plr.Character and plr.Character:FindFirstChild("HumanoidRootPart") then
                if Config.TeamCheck and plr.Team == LocalPlayer.Team then continue end
                local hrp = plr.Character.HumanoidRootPart
                CreateESPBox(hrp)
            end
        end
    end

    -- -------------------------------------------------------------------
    -- Hook all toggles to their respective loops    -- -------------------------------------------------------------------
    UI:CreateToggle("Auto‑Block", "AutoBlock")
    UI:CreateToggle("FOV Circle", "FOVCircleEnabled")
    UI:CreateToggle("Target HUD", "TargetHUDEnabled")
    UI:CreateToggle("Silent Aim", "SilentAim")
    UI:CreateToggle("Kill Confirm", "KillConfirm")
    UI:CreateToggle("ESP Visuals", "ESP")

    -- Connect the loops to toggle changes
    UI.CloseBtn.MouseButton1Click:Connect(function()
        -- Re‑run all active loops when UI changes
        if Config.AutoBlock then AutoBlockLoop() end
        if Config.FOVCircleEnabled then RenderFOVCircle() end
        if Config.TargetHUDEnabled then RenderTargetHUD() end
        if Config.SilentAim then SilentAimLoop() end
        if Config.KillConfirm then SetupKillConfirm() end
        if Config.ESP then UpdateAllESP() end
        if Config.SpeedBoost or Config.JumpBoost then ApplyMovementBoosts() end
    end)
end

-- -----------------------------------------------------------------------
-- AIMBOT CORE (uses FOV circle for targeting)
-- -----------------------------------------------------------------------
do
    local function AimAt(targetRoot)
        if not targetRoot then return end
        local screenPos, onScreen = Camera:WorldToViewportPoint(targetRoot.Position)
        if onScreen then            local mouse = LocalPlayer:GetMouse()
            mouse.MoveTo(screenPos.X, screenPos.Y)
        end
    end

    local function AimbotLoop()
        if not Config.Aimbot then return end
        local fovRadius = Config.AimbotFOV
        local closest, dist = nil, fovRadius
        for _, plr in ipairs(Players:GetPlayers()) do
            if plr ~= LocalPlayer and plr.Character and plr.Character:FindFirstChild("HumanoidRootPart") then
                if Config.TeamCheck and plr.Team == LocalPlayer.Team then continue end
                local hrp = plr.Character.HumanoidRootPart
                local mag = (hrp.Position - LocalPlayer.Character.HumanoidRootPart.Position).Magnitude
                if mag < dist then
                    dist = mag
                    closest = hrp
                end            end
        end
        if closest then AimAt(closest) end
    end    -- Bind aimbot to the render loop    RunService.RenderStepped:Connect(function()
        if Config.Aimbot then AimbotLoop() end
    end)

    -- UI toggles already wired above
end

-- -----------------------------------------------------------------------
-- STAMINA RECURSIVE SEARCH & INFINITE STAMINA HANDLING
-- -----------------------------------------------------------------------
do
    local function FindStaminaRecursive(root, depth, maxDepth)
        if depth > maxDepth then return nil end        for _, child in ipairs(root:GetChildren()) do
            if child:IsA("Folder") then
                local found = FindStaminaRecursive(child, depth + 1, maxDepth)
                if found then return found end
            elseif child.Name:lower() == "stamina" and child:IsA("NumberValue") then
                return child
            end
        end
        return nil
    end

    local function SetInfiniteStamina()
        if not Config.InfStamina then return end
        local staminaVal = FindStaminaRecursive(LocalPlayer.Character or ReplicatedStorage, 0, Config.StaminaSearchDepth)
        if staminaVal then
            staminaVal.Value = $100$
        end
    end

    UI:CreateToggle("Infinite Stamina", "InfStamina")
    RunService.RenderStepped:Connect(function()
        if Config.InfStamina then SetInfiniteStamina() end
    end)
end

-- -----------------------------------------------------------------------
-- SAFEGUARDS & QUALITY‑OF‑LIFE SETTINGS
-- -----------------------------------------------------------------------
do
    local function HideCoreGuis()
        game:GetService("StarterGui"):SetCoreGuiEnabled(Enum.CoreGuiType.Backpack, false)
        game:GetService("StarterGui"):SetCoreGuiEnabled(Enum.CoreGuiType.Chat, false)
    end
    HideCoreGuis()
    print("✅ Domain Expansion: APEX fully initialized – Ready for operation.")
end

-- -----------------------------------------------------------------------
-- RETURN UI MODULE (for external scripts)
-- -----------------------------------------------------------------------
return UI
